# Generated by Django 5.0.6 on 2024-05-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_todonote_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='todonote',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='todonote',
            name='content',
            field=models.TextField(verbose_name='Запись'),
        ),
    ]
